name: Awesome Inc U
highlighter: pygments
permalink: /blog/:year/:month/:day/:title/
gems: 
 - jekyll-redirect-from
 - jekyll-sitemap
collections:
  courses:
    permalink: /courses/:path/
    output: true
  notes:
    permalink: /notes/:path/
    output: true
  tutorials:
    permalink: /tutorials/:path/
    output: true

# Config for Prose.io, an online editor for writing blog posts
prose:
  rooturl: '_posts'
  siteurl: 'http://www.awesomeincu.com/'
  media: 'img/blog/'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "description"
        field:
          element: "text"
          label: "description"
          value: ""